name:                symbol-sets
synopsis:            Type-level sets of Symbols
category:            Data
version:             0.1.0.0
github:              "michaeljklein/symbol-sets"
license:             BSD3
author:              "Michael J. Klein"
maintainer:          "lambdamichael@gmail.com"
copyright:           "2018 Michael J. Klein"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaeljklein/symbol-sets#readme>

dependencies:
- base >= 4.7 && < 5
- reflection
- constraints
- deepseq

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    - Data.Set.Symbol
    - Data.Type.Set

tests:
  symbol-sets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symbol-sets
    - should-not-typecheck
    - HUnit

